<?php require('mng_header.phtml'); mng_header('import exam')?>
<body>
    <body class="mng_home">
        <div class="body container">
            <div class="main_container">
                <?php require('mng_menu.phtml') ?>
                <?php require('header_menu.phtml') ?>
                <div class="right_col mng_user">
                    <div class="box_import_file">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 pad_0">
                            <div class="x_panel mag5">
                                    <div class="x_content">
                                        <div class="import_exam">
                                            <div class="import_btn">
                                                <button type="submit" class="relative_import bod_radius0 btn btn-primary">Choose Excel</button>
                                                <input type="file" class="import_file">
                                                <button class="btn btn-success bod_radius0" id="btn_import">Import</button>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="show_data">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 pad_0">
                            <div class="x_panel mag5">
                                    <div class="x_content">
                                        <table class="table data_exam">
                                            <thead>
                                                <tr>
                                                    <th><input type="checkbox" class="option_que radio_que" name="" id=""/></th>
                                                    <th>STT</th>
                                                    <th>Mã đề</th>
                                                    <th>Tên đề</th>
                                                    <th>Môn</th>
                                                    <th>Thời gian</th>
                                                    <th>Tổng Số câu</th>
                                                    <th>Random câu</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="show_data_exam" id="show_data_exam"></tbody>
                                        </table>
                                        <div class="page_exam text-right">
                                            <div class="pagination" id="pagination_exam"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="section_FileReader" id="readFileExam">
                    <div class="width_FileReader">
                        <div class="header_FileReader pad-bot-15 grid-title">
                            <div class="title_left">
                                <div class="max-width400">
                                    <div class="grid-top">
                                        <div class="id_file_exam">
                                            <span>Mã đề: </span><p><input type="text" name="IdExam"  class="input_file_exam"></p>
                                        </div>
                                        <div class="time_file_exam">
                                            <span>Thời gian: </span><p><input type="number" name="TimeExam" class="input_file_exam"/></p>
                                        </div>
                                    </div>
                                    <div class="name_file_exam">
                                        <span>Tên đề: </span> <p><input type="text" name="NameExam" class="input_file_exam" /></p>
                                    </div>
                                    <div class="grid-top">
                                        <div class="subject_file_exam">
                                            <span>Môn học: </span> 
                                            <p><select class='input_file_exam' id="subject_file_import" name="SubjectExam"></select></p>
                                        </div>
                                        <div class="random_exam">
                                            <span>Số lượng câu: </span><p><input type="number" name="RandomNumber" class="input_file_exam"/></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="close_right">
                                <p class="close_FileRead" id="close_FileRead">X</p>
                            </div>
                        </div>
                        <div class="content_FileReader pad-t15 border-wapper" id="show_question_file"></div>
                        <div class="section_pagination">
                            <div class="pagination" id="pagination_que"></div>
                        </div>
                        <div class="btn_FileReader pad-t15 text-right">
                            <button class="btn btn-primary bod_radius0" id="NewImportExam">Create Exam</button>
                        </div>
                    </div>
                </div>
                <div class="EditExamId" id="EditExamId">
                    <div class="width_FileReader">
                        <div class="header_FileReader pad-bot-15 grid-title">
                            <div class="title_left">
                                <div class="max-width400">
                                    <div class="grid-top">
                                        <div class="id_file_exam">
                                            <span>Mã đề: </span><p><input readonly type="text" name="UpdateIdExam"  class="input_file_exam not-allow"></p>
                                        </div>
                                        <div class="time_file_exam">
                                            <span>Thời gian: </span><p><input type="number" name="UpdateTimeExam" class="input_file_exam"/></p>
                                        </div>
                                    </div>
                                    <div class="name_file_exam">
                                        <span>Tên đề: </span> <p><input type="text" name="UpdateNameExam" class="input_file_exam" /></p>
                                    </div>
                                    <div class="grid-top">
                                        <div class="subject_file_exam">
                                            <span>Môn học: </span> 
                                            <p><select class='input_file_exam' id="subject_update_exam" name="UpdateSubjectExam"></select></p>
                                        </div>
                                        <div class="random_exam">
                                            <span>Số lượng câu: </span><p><input type="number" name="UpdateRandomNumber" class="input_file_exam"/></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="close_right">
                                <p class="close_FileRead" id="close_edit_exam">X</p>
                            </div>
                        </div>
                        <div class="content_FileReader pad-t15 border-wapper" id="showQuestionExam"></div>
                        <div class="section_pagination">
                            <div class="pagination" id="pageQuestions"></div>
                        </div>
                        <div class="btn_FileReader text-right">
                            <button class="btn btn-primary bod_radius0" id="UpdateImportExam">Update Exam</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script src="<?=PATH?>/public/js/import_exam.js"></script>
</html>