<?php

function mng_header($title){
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="<?=PATH?>/public/js/jquery.min.js"></script>
        <script src="<?=PATH?>/public/js/xlsx.full.min.js"></script>
        <link rel="stylesheet" href="<?=PATH?>/public/css/admin_style.css">
        <script src="<?=PATH?>/public/js/data.js"></script>
        <script src="<?=PATH?>/public/js/mng_script.js"></script>
        <title><?php echo $title ?></title>
        <script>
            function notification(name) {
                setTimeout(function () {
                    $(name).show();
                    $('.the_notification').css('top', '5px');
                }, 500);
                setTimeout(function () {
                    $(name).hide();
                    $('.the_notification').css('top', '35px');
                }, 5000);
            }
        </script>
    </head>
<?php
}