<?php require('mng_header.phtml'); mng_header('Thông báo')?>

<body>

    <body class="mng_home">
        <div class="body container">
            <div class="main_container">
                <?php require('mng_menu.phtml') ?>
                <?php require('header_menu.phtml') ?>
                <div class="right_col mng_user">
                    <div class="table_right">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="x_title">
                                            <h2>Các thông báo</h2>
                                        </div>
                                        <div class="Notifications_content" id="display_all_data">
                                            
                                            <!-- <div class="item_feedback row">
                                                <div class="noti_feedback">
                                                    <span class="user_feedback">Nguyenson </span>
                                                    <span class="time_feedback"> 20-9-2016 </span>
                                                </div>
                                                <div class="question_feedback">
                                                    <div class="exam_text">
                                                        <span>Đánh giá: </span>
                                                        <span class="content_feedback" >Bottom Menu layout is useful for those users who wants menu in bottom of the page.</span>
                                                    </div>
                                                    <div class="exam_text">
                                                        <span>Tên đề: </span>
                                                        <span class="exam_feedback">HTML Markup</span>
                                                    </div>
                                                    <div class="question_text">
                                                        <span>Câu hỏi: </span>
                                                        <span class="question_feeback">Bottom Menu layout is useful for those users who wants menu in bottom of the page.</span>
                                                    </div>
                                                </div>
                                            </div> -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script src="<?=PATH?>/public/js/notificationHanding.js"></script>
    </html>