<?php require('mng_header.phtml'); mng_header('Users management')?>

<body>

    <body class="mng_home">
        <div class="body container">
            <div class="main_container">
                <?php require('mng_menu.phtml') ?>
                <?php require('header_menu.phtml') ?>
                <div class="right_col mng_user">
                    <div class="table_right">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <div class="x_title">
                                            <h2>All users</h2>
                                        </div>
                                        <div class="table-responsive">
                                            <table class="table table-striped jambo_table bulk_action">
                                                <thead>
                                                    <tr class="headings">
                                                        <th class="column-title">STT</th>
                                                        <th class="column-title">Email</th>
                                                        <th class="column-title">Last name</th>
                                                        <th class="column-title">First name</th>
                                                        <th class="column-title">Username</th>
                                                        <th class="column-title">Status</th>
                                                        <th class="column-title">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="display_users"></tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="info_user">
                        <div class="box_wapper">
                            <div class="box_width_max">
                                <div class="box_background">
                                    <section class="in_title">
                                        <p>infomation user</p>
                                    </section>
                                    <section class="personal_info">

                                    </section>
                                    <section class="box_content">
                                        <table class="table table-striped jambo_table bulk_action">
                                            <thead>
                                                <tr class="headings">
                                                    <th class="column-title">STT</th>
                                                    <th class="column-title">exam</th>
                                                    <th class="column-title">Point</th>
                                                </tr>
                                            </thead>
                                            <tbody id="display_info"></tbody>
                                        </table>
                                    </section>
                                    <section class="btn_footer text-right">
                                        <button class="btn_seen" type="submit">Seen</button>
                                    </section>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script src="<?=PATH?>/public/js/userHanding.js"></script>
    </html>